### ISSUE TITLE
Example capture.py doesn't work with sampling frequency less than 20kHz

### ISSUE THREAD

**Issue by gotlaufs** [jetperch/pyjoulescope_examples#13]
Hello!
When I try to use `capture.py` example with frequency lower than 20 kHz it crashes:

```
$ python pyjoulescope_examples/bin/capture.py --frequency 10000 cap.jls
Capturing data from JS110-001783: type CTRL-C to stop
<joulescope.data_recorder.DataRecorder object at 0x7f467c0ec0d0> stream_notify() exception
Traceback (most recent call last):
  File "/home/robert/code/test/remote-js/venv/lib/python3.11/site-packages/joulescope/v1/device.py", line 430, in _stream_process_call
    rv |= bool(fn(*args, **kwargs))
               ^^^^^^^^^^^^^^^^^^^
  File "/home/robert/code/test/remote-js/venv/lib/python3.11/site-packages/joulescope/data_recorder.py", line 205, in stream_notify
    raise ValueError('stream_buffer length too small.  %s > %s' %
ValueError: stream_buffer length too small.  400000 > 300000

```

Python version: `3.11.4`
Python modules:
```
$ pip freeze                                                                                                                                                              
certifi==2023.7.22                                                                                                                                                        
charset-normalizer==3.2.0                                                                                                                                                 
contourpy==1.1.0                                                                                                                                                          
cycler==0.11.0                                                                                                                                                            
fonttools==4.42.1
idna==3.4
joulescope==1.1.9
joulescope-server==0.1.5
kiwisolver==1.4.5
matplotlib==3.7.2
numpy==1.25.2
packaging==23.1
Pillow==10.0.0
psutil==5.9.5
pyjls==0.7.3
pyjoulescope-driver==1.3.18
pymonocypher==3.1.3.2
pyparsing==3.0.9
python-dateutil==2.8.2
requests==2.31.0
six==1.16.0
urllib3==2.0.4
```

JouleScope JS110 S/N 001783

**Comment by mliberty1** [comment]
Hi @gotlaufs !  Are you trying to simply record from the command line?  If so, you can use the new [pyjoulescope_driver record ](https://github.com/jetperch/joulescope_driver/blob/main/pyjoulescope_driver/entry_points/record.py) entry-point directly:

```
python -m pyjoulescope_driver record --frequency 10000 cap.jls
```

This records to JLS v2, which I now recommend over JLS v1.  JLS v2 has much faster read performance for instantaneous browsing in the Joulescope UI.

Does this work for you?

**Comment by gotlaufs** [comment]
Yes, this is exactly what I was trying to do.
I was not aware of this entry point
Thank you!

The issue with the example still remains though. Up to you to decide what to do about it.

**Comment by mliberty1** [comment]
At least for now, we will not fix this.  JLS v1 is on the way out and JLS v2 is the future.  You can make `capture.py` work if you add `--jls 2` to your command:

```
python pyjoulescope_examples/bin/capture.py --jls 2 --frequency 10000 cap.jls
```

However, the `pyjoulescope_driver record` entry point has more flexibility and can record all of the signals, not just current, voltage, and power.

The only remaining issue with JLS v2 compared to v1 is that the reader does not handle file truncation yet.  However, we are already working on this and should have it addressed soon.  See https://github.com/jetperch/pyjoulescope_ui/issues/217.
